import { createFileRoute, notFound } from "@tanstack/react-router";
import { useState, useEffect } from "react";
import { createPortal } from "react-dom";
import { ArrowRight, ArrowLeft, Phone, MessageCircle, ScrollText, HeartHandshake, Gem, Compass, Clock, Layers, CheckCircle2, Menu, X, MapPin, Mail } from "lucide-react";
import logoAsset from "@/assets/logo.png.asset.json";
const LOGO = logoAsset.url;

const CONTACT = {
  email: "hello@astroview.app",
  phone: "+91-9319843151",
  address: ["Unit No.202, Second Floor, Plot No. 103,", "Block A, Sector 63 Noida,", "Gautam Budh Nagar UP – 201301"],
};

export const Route = createFileRoute("/services/$slug")({
  head: ({ params }) => {
    const s = services.find((x) => x.slug === params.slug);
    return {
      meta: [
        { title: s ? `${s.title} — AstroView` : "Service — AstroView" },
        { name: "description", content: s?.short ?? "Vedic astrology services from AstroView." },
      ],
    };
  },
  loader: ({ params }) => {
    const s = services.find((x) => x.slug === params.slug);
    if (!s) throw notFound();
    return s;
  },
  component: ServiceDetail,
});

const services = [
  {
    slug: "live-call",
    icon: Phone,
    title: "Live Call Consultations",
    short: "One-on-one voice sessions with seasoned astrologers, anywhere you are.",
    long: "Connect directly with a vetted astrologer over a live voice call. Whether you have a pressing career question, a relationship concern, or simply want to understand your chart better, our call consultations offer a personal, real-time conversation tailored entirely to your situation. Sessions are available in Hindi and English.",
    duration: "30–60 min",
    mode: "Voice call",
    highlights: [
      "Real-time conversation with a vetted astrologer",
      "Available in Hindi and English",
      "No scripted responses — your questions drive the session",
      "Covers career, relationships, health, timing, and more",
      "Session notes available on request",
    ],
    whatToExpect: "Before your session, share your birth date, time, and place so the astrologer can prepare your chart in advance. During the call, you lead with your questions — there's no set agenda. The astrologer will explain the planetary context behind their observations, so you leave understanding the reasoning, not just the conclusion.",
  },
  {
    slug: "chat-readings",
    icon: MessageCircle,
    title: "Chat Readings",
    short: "Quick, private chat sessions for moments when you need clarity, fast.",
    long: "Not every question needs a full hour. Our chat readings let you ask specific questions and receive considered, written responses from a real astrologer — not a bot. Perfect for a quick check on timing, a yes/no that deserves more than a coin flip, or a second opinion before a decision.",
    duration: "15–30 min",
    mode: "Text chat",
    highlights: [
      "Written responses from a real astrologer",
      "Ideal for focused, specific questions",
      "Private and asynchronous — respond at your pace",
      "Available in Hindi and English",
      "Conversation transcript saved for your reference",
    ],
    whatToExpect: "You submit your question with your birth details. An astrologer reviews your chart and responds with a thoughtful written answer — typically within a few hours. You can follow up with clarifying questions within the session window. Chat readings are best suited for specific, bounded questions rather than open-ended life guidance.",
  },
  {
    slug: "janam-kundli",
    icon: ScrollText,
    title: "Janam Kundli",
    short: "A meticulously cast Vedic birth chart that decodes your life's blueprint.",
    long: "Your Janam Kundli (birth chart) is the foundation of Vedic astrology. We prepare a precise Parashari kundli from your birth date, time and place — then an astrologer actually reads it and provides a written interpretation covering your personality, health, career, relationships and spiritual path.",
    duration: "Delivered in 24–48 hrs",
    mode: "Written report + call",
    highlights: [
      "Precise Parashari Kundli from your exact birth data",
      "Interpreted by a human astrologer — not generated by software",
      "Covers all 12 houses and key planetary placements",
      "Includes Dasha (planetary period) analysis",
      "Optional follow-up call to discuss your report",
    ],
    whatToExpect: "Provide your birth date, time, and place. Our astrologer prepares a detailed written report — typically 15–25 pages — covering your ascendant, planetary placements, house analysis, current Dasha period, and general life themes. You'll receive the report within 48 hours, along with the option to schedule a 30-minute follow-up call.",
  },
  {
    slug: "love-compatibility",
    icon: HeartHandshake,
    title: "Love & Compatibility",
    short: "Guna Milan and synastry insights to understand the bonds that matter.",
    long: "Relationship guidance rooted in classical Guna Milan (36-point matching system) combined with modern synastry analysis. We look beyond a compatibility score to explain the actual dynamics at play — where you naturally align, where friction might arise, and how to navigate it together.",
    duration: "45–60 min or written report",
    mode: "Call or report",
    highlights: [
      "Classical Guna Milan (36-point Ashtakoot matching)",
      "Synastry analysis of both charts together",
      "Honest assessment — not just what you want to hear",
      "Identifies areas of natural alignment and potential friction",
      "Available as a written report or live call",
    ],
    whatToExpect: "Provide the birth details for both individuals. We conduct a full Guna Milan analysis alongside a synastry reading of both charts. The output explains what the matching score means in practice — which Gunas carry weight for long-term compatibility, and how the planetary relationships between both charts interact. This is not a verdict — it's a map.",
  },
  {
    slug: "gemstone-remedies",
    icon: Gem,
    title: "Gemstone & Remedies",
    short: "Personalised gemstone, mantra and ritual suggestions rooted in tradition.",
    long: "Remedies in Vedic astrology are tools for working with planetary energies, not magic shortcuts. Based on a reading of your chart, we suggest gemstones, mantras, colours, fasting days or simple daily rituals that are personally calibrated — never a generic list from a website.",
    duration: "Included with kundli or standalone",
    mode: "Written report",
    highlights: [
      "Gemstone recommendations calibrated to your chart",
      "Mantra suggestions with correct pronunciation guidance",
      "Practical daily rituals — no superstition, no pressure",
      "Colour and lifestyle adjustments for planetary support",
      "Explained with full reasoning — you'll know why each remedy is suggested",
    ],
    whatToExpect: "A remedy report is most meaningful when prepared alongside a Kundli reading, since it requires a thorough understanding of your chart's strengths and weaknesses. Standalone remedy readings are also available. Every suggestion comes with a clear explanation of which planet it addresses and how it's intended to help.",
  },
  {
    slug: "career-direction",
    icon: Compass,
    title: "Career & Direction",
    short: "Map planetary cycles to make confident decisions about your work and path.",
    long: "Career decisions are among the most consequential choices you'll make. We use Dasha timelines (planetary period cycles) alongside your 10th house analysis to identify periods of opportunity, transition and consolidation — so you can act with confidence, not just hope.",
    duration: "45–60 min",
    mode: "Voice call",
    highlights: [
      "10th house and career-related planetary analysis",
      "Dasha timeline — understand where you are in your cycle",
      "Identify periods of opportunity, change, and consolidation",
      "Guidance on timing of decisions: job changes, business starts, relocations",
      "Honest framing — we won't manufacture urgency",
    ],
    whatToExpect: "Share your birth details and the specific career question you're navigating — whether that's a job change, a business decision, a relocation, or general uncertainty about direction. The session draws on your 10th house, its lord, and the current Dasha period to give you a timing-aware picture of where you are and what's ahead.",
  },
];

function Header() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 16); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  useEffect(() => { document.body.style.overflow = menuOpen ? "hidden" : ""; return () => { document.body.style.overflow = ""; }; }, [menuOpen]);
  const navLinks = [{ label: "Home", href: "/" }, { label: "Services", href: "/services" }, { label: "About", href: "/about" }, { label: "Contact", href: "/#contact" }];
  return (
    <>
    <header className={`sticky top-0 z-50 transition-all duration-300 ${scrolled ? "backdrop-blur-xl bg-background/80 border-b border-border/50 shadow-[0_1px_12px_oklch(0.58_0.18_42_/_0.08)]" : "backdrop-blur-xl bg-background/70 border-b border-border/50"}`}>
      <div className="mx-auto max-w-7xl px-6 py-3 h-18 flex items-center justify-between">
        <a href="/" className="flex items-center gap-2.5 shrink-0"><img src={LOGO} alt="AstroView" className="h-10 w-10" /><span className="text-xl font-display font-semibold tracking-tight">Astro<span className="text-primary">View</span></span></a>
        <nav className="hidden md:flex items-center gap-7">{navLinks.map((l) => <a key={l.href} href={l.href} className="text-sm text-muted-foreground hover:text-foreground transition-colors">{l.label}</a>)}</nav>
        <a href="/#contact" className="hidden md:inline-flex items-center gap-1.5 rounded-full bg-gradient-primary px-5 py-2.5 text-sm font-medium text-primary-foreground shadow-soft hover:opacity-95 transition">Get in touch <ArrowRight className="h-4 w-4" /></a>
        <button onClick={() => setMenuOpen(true)} className="md:hidden p-2 text-foreground rounded-lg hover:bg-accent transition"><Menu className="h-5 w-5" /></button>
      </div>

    </header>

    {typeof document !== "undefined" && createPortal(
      <>
      {menuOpen && <div className="fixed inset-0 z-[60] bg-foreground/40 backdrop-blur-sm md:hidden" onClick={() => setMenuOpen(false)} />}
      <div className={`fixed top-0 right-0 z-[70] h-full w-[280px] bg-background border-l border-border shadow-2xl flex flex-col md:hidden transition-transform duration-300 ${menuOpen ? "translate-x-0" : "translate-x-full"}`}>
        <div className="flex items-center justify-between px-6 py-5 border-b border-border"><div className="flex items-center gap-2"><img src={LOGO} alt="" className="h-8 w-8" /><span className="font-display font-semibold text-lg">Astro<span className="text-primary">View</span></span></div><button onClick={() => setMenuOpen(false)} className="p-1.5 rounded-full hover:bg-accent transition"><X className="h-5 w-5" /></button></div>
        <nav className="flex flex-col gap-1 p-4 flex-1">{navLinks.map((l) => <a key={l.href} href={l.href} onClick={() => setMenuOpen(false)} className="px-4 py-3.5 rounded-xl text-base font-medium hover:bg-accent transition">{l.label}</a>)}</nav>
        <div className="p-5 border-t border-border"><a href="/#contact" onClick={() => setMenuOpen(false)} className="flex items-center justify-center gap-2 w-full rounded-full bg-gradient-primary px-5 py-3.5 text-sm font-medium text-primary-foreground">Get in touch <ArrowRight className="h-4 w-4" /></a></div>
      </div>
      </>,
      document.body
    )}
    </>
  );
}

function ServiceDetail() {
    const s = Route.useLoaderData() as (typeof services)[number];

if (!s) return null;
  const currentIdx = services.findIndex((x) => x.slug === s.slug);
  const prev = services[currentIdx - 1];
  const next = services[currentIdx + 1];

  return (
    <div className="min-h-screen bg-background text-foreground overflow-x-hidden">
      <Header />

      {/* Breadcrumb */}
      <div className="mx-auto max-w-7xl px-6 pt-6">
        <a href="/services" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors">
          <ArrowLeft className="h-4 w-4" /> All services
        </a>
      </div>

      {/* Hero */}
      <section className="relative isolate overflow-hidden py-14 md:py-20">
        <div className="absolute inset-0 bg-gradient-hero -z-10" />
        <div className="mx-auto max-w-7xl px-6 grid lg:grid-cols-[1fr_auto] gap-10 items-start">
          <div>
            <div className="h-16 w-16 rounded-2xl bg-gradient-primary text-primary-foreground flex items-center justify-center shadow-glow mb-6"><s.icon className="h-7 w-7" /></div>
            <div className="flex flex-wrap items-center gap-3 mb-5">
              <span className="inline-flex items-center gap-1.5 rounded-full border border-border bg-card px-3 py-1.5 text-xs text-muted-foreground"><Clock className="h-3.5 w-3.5" />{s.duration}</span>
              <span className="inline-flex items-center gap-1.5 rounded-full border border-border bg-card px-3 py-1.5 text-xs text-muted-foreground"><Layers className="h-3.5 w-3.5" />{s.mode}</span>
              <span className="inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/5 px-3 py-1.5 text-xs font-medium text-primary-deep">Coming soon</span>
            </div>
            <h1 className="font-display font-semibold text-4xl md:text-6xl leading-tight tracking-tight">{s.title}</h1>
            <p className="mt-5 text-xl text-muted-foreground leading-relaxed max-w-2xl">{s.long}</p>
          </div>
          {/* Contact aside */}
          <div className="lg:w-72 shrink-0">
            <div className="rounded-3xl border border-border bg-card p-7 shadow-card space-y-5">
              <p className="text-xs uppercase tracking-[0.18em] text-muted-foreground">Interested? Reach out</p>
              <a href={`mailto:${CONTACT.email}`} className="flex items-center gap-3 group">
                <div className="h-9 w-9 rounded-lg border border-border flex items-center justify-center shrink-0 text-muted-foreground group-hover:border-primary group-hover:text-primary transition"><Mail className="h-4 w-4" /></div>
                <span className="text-sm text-foreground group-hover:text-primary transition break-all">{CONTACT.email}</span>
              </a>
              <a href={`tel:${CONTACT.phone}`} className="flex items-center gap-3 group">
                <div className="h-9 w-9 rounded-lg border border-border flex items-center justify-center shrink-0 text-muted-foreground group-hover:border-primary group-hover:text-primary transition"><Phone className="h-4 w-4" /></div>
                <span className="text-sm text-foreground group-hover:text-primary transition">{CONTACT.phone}</span>
              </a>
              <div className="pt-2 border-t border-border">
                <a href="/#contact" className="flex items-center justify-center gap-2 w-full rounded-full bg-gradient-primary px-5 py-3 text-sm font-medium text-primary-foreground shadow-soft hover:opacity-95 transition">
                  Get in touch <ArrowRight className="h-4 w-4" />
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="py-14 md:py-20 bg-gradient-to-b from-background to-accent/30">
  <div className="mx-auto max-w-7xl px-6">
    <p className="text-xs uppercase tracking-[0.18em] text-muted-foreground mb-6">
      Other services
    </p>

    <div className="grid sm:grid-cols-2 gap-5">
      {[prev, next].filter(Boolean).map((other) => {
        const Icon = other!.icon;

        return (
          <a
            key={other!.slug}
            href={`/services/${other!.slug}`}
            className="group flex gap-5 rounded-2xl border border-border bg-card p-6 shadow-card hover:shadow-glow hover:-translate-y-0.5 transition-all duration-300"
          >
            <div className="h-12 w-12 rounded-xl bg-gradient-primary text-primary-foreground flex items-center justify-center shadow-soft shrink-0">
              <Icon className="h-5 w-5" />
            </div>

            <div className="flex-1 min-w-0">
              <h3 className="font-display font-semibold">
                {other!.title}
              </h3>

              <p className="mt-1 text-sm text-muted-foreground line-clamp-2">
                {other!.short}
              </p>

              <span className="mt-3 inline-flex items-center gap-1 text-xs font-medium text-primary-deep/80 group-hover:gap-2 transition-all">
                Learn more
                <ArrowRight className="h-3 w-3" />
              </span>
            </div>
          </a>
        );
      })}
    </div>

    <div className="mt-6 text-center">
      <a
        href="/services"
        className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition"
      >
        <ArrowLeft className="h-4 w-4" />
        View all services
      </a>
    </div>
  </div>
</section>

      {/* Footer */}
      <footer className="border-t border-border bg-card/40">
        <div className="mx-auto max-w-7xl px-6 py-10 flex flex-col md:flex-row justify-between gap-6 text-sm text-muted-foreground">
          <div className="flex items-center gap-2.5"><img src={LOGO} alt="" className="h-8 w-8" /><span className="font-display font-semibold text-foreground">Astro<span className="text-primary">View</span></span></div>
          <div className="flex items-center gap-2"><MapPin className="h-4 w-4 shrink-0" />{CONTACT.address[1]}</div>
          <div className="flex items-center gap-2"><Mail className="h-4 w-4 shrink-0" /><a href={`mailto:${CONTACT.email}`} className="hover:text-primary transition">{CONTACT.email}</a></div>
          <div className="flex items-center gap-2"><Phone className="h-4 w-4 shrink-0" /><a href={`tel:${CONTACT.phone}`} className="hover:text-primary transition">{CONTACT.phone}</a></div>
        </div>
        <div className="border-t border-border/60 px-6 py-4 max-w-7xl mx-auto flex justify-between text-xs text-muted-foreground">
          <p>© {new Date().getFullYear()} AstroView. All rights reserved.</p><p>KamleshKhyati Infosolution Pvt. Ltd.</p>
        </div>
      </footer>
    </div>
  );
}