/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RechargeRouteImport } from './routes/recharge'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TarotIndexRouteImport } from './routes/tarot/index'
import { Route as PujaIndexRouteImport } from './routes/puja/index'
import { Route as NumerologyIndexRouteImport } from './routes/numerology/index'
import { Route as HoroscopeIndexRouteImport } from './routes/horoscope/index'
import { Route as ConsultationIndexRouteImport } from './routes/consultation/index'
import { Route as TarotSpreadRouteImport } from './routes/tarot/$spread'
import { Route as PujaSlugRouteImport } from './routes/puja/$slug'
import { Route as NumerologyNumberRouteImport } from './routes/numerology/$number'
import { Route as HoroscopeSignRouteImport } from './routes/horoscope/$sign'
import { Route as ConsultationSlugRouteImport } from './routes/consultation/$slug'

const RechargeRoute = RechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotIndexRoute = TarotIndexRouteImport.update({
  id: '/tarot/',
  path: '/tarot/',
  getParentRoute: () => rootRouteImport,
} as any)
const PujaIndexRoute = PujaIndexRouteImport.update({
  id: '/puja/',
  path: '/puja/',
  getParentRoute: () => rootRouteImport,
} as any)
const NumerologyIndexRoute = NumerologyIndexRouteImport.update({
  id: '/numerology/',
  path: '/numerology/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopeIndexRoute = HoroscopeIndexRouteImport.update({
  id: '/horoscope/',
  path: '/horoscope/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationIndexRoute = ConsultationIndexRouteImport.update({
  id: '/consultation/',
  path: '/consultation/',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotSpreadRoute = TarotSpreadRouteImport.update({
  id: '/tarot/$spread',
  path: '/tarot/$spread',
  getParentRoute: () => rootRouteImport,
} as any)
const PujaSlugRoute = PujaSlugRouteImport.update({
  id: '/puja/$slug',
  path: '/puja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NumerologyNumberRoute = NumerologyNumberRouteImport.update({
  id: '/numerology/$number',
  path: '/numerology/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopeSignRoute = HoroscopeSignRouteImport.update({
  id: '/horoscope/$sign',
  path: '/horoscope/$sign',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationSlugRoute = ConsultationSlugRouteImport.update({
  id: '/consultation/$slug',
  path: '/consultation/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recharge': typeof RechargeRoute
  '/consultation/$slug': typeof ConsultationSlugRoute
  '/horoscope/$sign': typeof HoroscopeSignRoute
  '/numerology/$number': typeof NumerologyNumberRoute
  '/puja/$slug': typeof PujaSlugRoute
  '/tarot/$spread': typeof TarotSpreadRoute
  '/consultation/': typeof ConsultationIndexRoute
  '/horoscope/': typeof HoroscopeIndexRoute
  '/numerology/': typeof NumerologyIndexRoute
  '/puja/': typeof PujaIndexRoute
  '/tarot/': typeof TarotIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recharge': typeof RechargeRoute
  '/consultation/$slug': typeof ConsultationSlugRoute
  '/horoscope/$sign': typeof HoroscopeSignRoute
  '/numerology/$number': typeof NumerologyNumberRoute
  '/puja/$slug': typeof PujaSlugRoute
  '/tarot/$spread': typeof TarotSpreadRoute
  '/consultation': typeof ConsultationIndexRoute
  '/horoscope': typeof HoroscopeIndexRoute
  '/numerology': typeof NumerologyIndexRoute
  '/puja': typeof PujaIndexRoute
  '/tarot': typeof TarotIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/recharge': typeof RechargeRoute
  '/consultation/$slug': typeof ConsultationSlugRoute
  '/horoscope/$sign': typeof HoroscopeSignRoute
  '/numerology/$number': typeof NumerologyNumberRoute
  '/puja/$slug': typeof PujaSlugRoute
  '/tarot/$spread': typeof TarotSpreadRoute
  '/consultation/': typeof ConsultationIndexRoute
  '/horoscope/': typeof HoroscopeIndexRoute
  '/numerology/': typeof NumerologyIndexRoute
  '/puja/': typeof PujaIndexRoute
  '/tarot/': typeof TarotIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/recharge'
    | '/consultation/$slug'
    | '/horoscope/$sign'
    | '/numerology/$number'
    | '/puja/$slug'
    | '/tarot/$spread'
    | '/consultation/'
    | '/horoscope/'
    | '/numerology/'
    | '/puja/'
    | '/tarot/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/recharge'
    | '/consultation/$slug'
    | '/horoscope/$sign'
    | '/numerology/$number'
    | '/puja/$slug'
    | '/tarot/$spread'
    | '/consultation'
    | '/horoscope'
    | '/numerology'
    | '/puja'
    | '/tarot'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/recharge'
    | '/consultation/$slug'
    | '/horoscope/$sign'
    | '/numerology/$number'
    | '/puja/$slug'
    | '/tarot/$spread'
    | '/consultation/'
    | '/horoscope/'
    | '/numerology/'
    | '/puja/'
    | '/tarot/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RechargeRoute: typeof RechargeRoute
  ConsultationSlugRoute: typeof ConsultationSlugRoute
  HoroscopeSignRoute: typeof HoroscopeSignRoute
  NumerologyNumberRoute: typeof NumerologyNumberRoute
  PujaSlugRoute: typeof PujaSlugRoute
  TarotSpreadRoute: typeof TarotSpreadRoute
  ConsultationIndexRoute: typeof ConsultationIndexRoute
  HoroscopeIndexRoute: typeof HoroscopeIndexRoute
  NumerologyIndexRoute: typeof NumerologyIndexRoute
  PujaIndexRoute: typeof PujaIndexRoute
  TarotIndexRoute: typeof TarotIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recharge': {
      id: '/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof RechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot/': {
      id: '/tarot/'
      path: '/tarot'
      fullPath: '/tarot/'
      preLoaderRoute: typeof TarotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puja/': {
      id: '/puja/'
      path: '/puja'
      fullPath: '/puja/'
      preLoaderRoute: typeof PujaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numerology/': {
      id: '/numerology/'
      path: '/numerology'
      fullPath: '/numerology/'
      preLoaderRoute: typeof NumerologyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscope/': {
      id: '/horoscope/'
      path: '/horoscope'
      fullPath: '/horoscope/'
      preLoaderRoute: typeof HoroscopeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation/': {
      id: '/consultation/'
      path: '/consultation'
      fullPath: '/consultation/'
      preLoaderRoute: typeof ConsultationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot/$spread': {
      id: '/tarot/$spread'
      path: '/tarot/$spread'
      fullPath: '/tarot/$spread'
      preLoaderRoute: typeof TarotSpreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puja/$slug': {
      id: '/puja/$slug'
      path: '/puja/$slug'
      fullPath: '/puja/$slug'
      preLoaderRoute: typeof PujaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numerology/$number': {
      id: '/numerology/$number'
      path: '/numerology/$number'
      fullPath: '/numerology/$number'
      preLoaderRoute: typeof NumerologyNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscope/$sign': {
      id: '/horoscope/$sign'
      path: '/horoscope/$sign'
      fullPath: '/horoscope/$sign'
      preLoaderRoute: typeof HoroscopeSignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation/$slug': {
      id: '/consultation/$slug'
      path: '/consultation/$slug'
      fullPath: '/consultation/$slug'
      preLoaderRoute: typeof ConsultationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RechargeRoute: RechargeRoute,
  ConsultationSlugRoute: ConsultationSlugRoute,
  HoroscopeSignRoute: HoroscopeSignRoute,
  NumerologyNumberRoute: NumerologyNumberRoute,
  PujaSlugRoute: PujaSlugRoute,
  TarotSpreadRoute: TarotSpreadRoute,
  ConsultationIndexRoute: ConsultationIndexRoute,
  HoroscopeIndexRoute: HoroscopeIndexRoute,
  NumerologyIndexRoute: NumerologyIndexRoute,
  PujaIndexRoute: PujaIndexRoute,
  TarotIndexRoute: TarotIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
