/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TarotIndexRouteImport } from './routes/tarot/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as NumerologyIndexRouteImport } from './routes/numerology/index'
import { Route as HoroscopeIndexRouteImport } from './routes/horoscope/index'
import { Route as TarotSpreadRouteImport } from './routes/tarot/$spread'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as NumerologyNumberRouteImport } from './routes/numerology/$number'
import { Route as HoroscopeSignRouteImport } from './routes/horoscope/$sign'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotIndexRoute = TarotIndexRouteImport.update({
  id: '/tarot/',
  path: '/tarot/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const NumerologyIndexRoute = NumerologyIndexRouteImport.update({
  id: '/numerology/',
  path: '/numerology/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopeIndexRoute = HoroscopeIndexRouteImport.update({
  id: '/horoscope/',
  path: '/horoscope/',
  getParentRoute: () => rootRouteImport,
} as any)
const TarotSpreadRoute = TarotSpreadRouteImport.update({
  id: '/tarot/$spread',
  path: '/tarot/$spread',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NumerologyNumberRoute = NumerologyNumberRouteImport.update({
  id: '/numerology/$number',
  path: '/numerology/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopeSignRoute = HoroscopeSignRouteImport.update({
  id: '/horoscope/$sign',
  path: '/horoscope/$sign',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/horoscope/$sign': typeof HoroscopeSignRoute
  '/numerology/$number': typeof NumerologyNumberRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tarot/$spread': typeof TarotSpreadRoute
  '/horoscope/': typeof HoroscopeIndexRoute
  '/numerology/': typeof NumerologyIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tarot/': typeof TarotIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/horoscope/$sign': typeof HoroscopeSignRoute
  '/numerology/$number': typeof NumerologyNumberRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tarot/$spread': typeof TarotSpreadRoute
  '/horoscope': typeof HoroscopeIndexRoute
  '/numerology': typeof NumerologyIndexRoute
  '/services': typeof ServicesIndexRoute
  '/tarot': typeof TarotIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/horoscope/$sign': typeof HoroscopeSignRoute
  '/numerology/$number': typeof NumerologyNumberRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/tarot/$spread': typeof TarotSpreadRoute
  '/horoscope/': typeof HoroscopeIndexRoute
  '/numerology/': typeof NumerologyIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/tarot/': typeof TarotIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/horoscope/$sign'
    | '/numerology/$number'
    | '/services/$slug'
    | '/tarot/$spread'
    | '/horoscope/'
    | '/numerology/'
    | '/services/'
    | '/tarot/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/horoscope/$sign'
    | '/numerology/$number'
    | '/services/$slug'
    | '/tarot/$spread'
    | '/horoscope'
    | '/numerology'
    | '/services'
    | '/tarot'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/horoscope/$sign'
    | '/numerology/$number'
    | '/services/$slug'
    | '/tarot/$spread'
    | '/horoscope/'
    | '/numerology/'
    | '/services/'
    | '/tarot/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HoroscopeSignRoute: typeof HoroscopeSignRoute
  NumerologyNumberRoute: typeof NumerologyNumberRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  TarotSpreadRoute: typeof TarotSpreadRoute
  HoroscopeIndexRoute: typeof HoroscopeIndexRoute
  NumerologyIndexRoute: typeof NumerologyIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  TarotIndexRoute: typeof TarotIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot/': {
      id: '/tarot/'
      path: '/tarot'
      fullPath: '/tarot/'
      preLoaderRoute: typeof TarotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numerology/': {
      id: '/numerology/'
      path: '/numerology'
      fullPath: '/numerology/'
      preLoaderRoute: typeof NumerologyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscope/': {
      id: '/horoscope/'
      path: '/horoscope'
      fullPath: '/horoscope/'
      preLoaderRoute: typeof HoroscopeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarot/$spread': {
      id: '/tarot/$spread'
      path: '/tarot/$spread'
      fullPath: '/tarot/$spread'
      preLoaderRoute: typeof TarotSpreadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numerology/$number': {
      id: '/numerology/$number'
      path: '/numerology/$number'
      fullPath: '/numerology/$number'
      preLoaderRoute: typeof NumerologyNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscope/$sign': {
      id: '/horoscope/$sign'
      path: '/horoscope/$sign'
      fullPath: '/horoscope/$sign'
      preLoaderRoute: typeof HoroscopeSignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HoroscopeSignRoute: HoroscopeSignRoute,
  NumerologyNumberRoute: NumerologyNumberRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  TarotSpreadRoute: TarotSpreadRoute,
  HoroscopeIndexRoute: HoroscopeIndexRoute,
  NumerologyIndexRoute: NumerologyIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  TarotIndexRoute: TarotIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
